[project]
name = "atividade2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "tensorflow",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "pandas",
    "numpy",
    "opencv-python",
    "tqdm>=4.67.1",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "pillow>=12.0.0",
]
